# Generated by Django 4.2.7 on 2025-07-27 08:35

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the notice (max 200 characters)', max_length=200)),
                ('content', models.TextField(help_text='Main content of the notice')),
                ('published', models.BooleanField(default=False, help_text='Whether this notice is visible to the public')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notice was created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the notice was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this notice', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Full name of the student applying for admission', max_length=100)),
                ('student_dob', models.DateField(help_text='Date of birth of the student')),
                ('enrolled_class', models.CharField(help_text='Class/Grade the student wants to enroll in', max_length=50)),
                ('address', models.TextField(help_text='Complete address of the student')),
                ('guardian_name', models.CharField(help_text="Full name of the student's guardian", max_length=100)),
                ('guardian_mobile', accounts.models.BangladeshiPhoneNumberField(help_text="Guardian's mobile number (Bangladeshi format: 01xxxxxxxxx)", max_length=11, unique=True)),
                ('guardian_email', models.EmailField(help_text="Guardian's email address", max_length=254, unique=True)),
                ('message', models.TextField(blank=True, help_text='Additional message or information from the guardian')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the admission application', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the application was submitted')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the application was last updated')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-date_submitted'],
                'indexes': [models.Index(fields=['status', '-date_submitted'], name='public_admi_status_e7dd35_idx'), models.Index(fields=['guardian_mobile'], name='public_admi_guardia_b2631d_idx'), models.Index(fields=['guardian_email'], name='public_admi_guardia_1c8fa4_idx'), models.Index(fields=['enrolled_class'], name='public_admi_enrolle_3510a9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='admissionapplication',
            constraint=models.UniqueConstraint(fields=('guardian_mobile',), name='unique_guardian_mobile'),
        ),
        migrations.AddConstraint(
            model_name='admissionapplication',
            constraint=models.UniqueConstraint(fields=('guardian_email',), name='unique_guardian_email'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['published', '-date_created'], name='public_noti_publish_020824_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['created_by'], name='public_noti_created_419730_idx'),
        ),
    ]
